{{- if .Values.snapshotsEnabled }}
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: default
  labels:
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
{{- with .Values.configuration }}
{{- with .volumeSnapshotLocation }}
  provider: {{ .name }}
{{ with .config }}
  config:
  {{- with .region }}
    region: {{ . }}
  {{- end }}
  {{- with .apitimeout }}
    apiTimeout: {{ . }}
  {{- end }}
  {{- with .resourceGroup }}
    resourceGroup: {{ . }}
  {{- end }}
  {{- with .snapshotLocation }}
    snapshotLocation: {{ . }}
  {{- end}}
  {{- with .project }}
    project: {{ . }}
  {{- end}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}